### ISSUE TITLE
Mine opened where mouse is on mouseup, not on mousedown

### ISSUE THREAD

**Issue by IBPX** [kudima/minesweeper#5]
# Expected behavior

If you press down on one mine, and move the mouse to another tile before letting go, nothing is opened.

# Actual behavior

If you press down on one mine, and move the mouse to another tile before letting go, the second tile is opened instead.

It seems to be opening the tile the mouse is over on mouseup, rather than only opening a tile if the mouse is over the same tile it pressed down on.

**Comment by kudima** [comment]
The expected behavior described would make the game unplayable when you click around the board at hight rate. In this regard the application seems to behave as intended, namely flip the tile on every "proper" left mouse button click. It might feel weird due to luck of visualization of what tile is actually going to be opened, so I implemented that.
